---
title: "Link_Jap2Latin_Fish"
author: "Akira Hirao"
date: "`r Sys.Date()`"
output:
  md_document:
    toc: true
    variant: markdown_github
  html_document:
    toc: true
---

# Linking Japanese name to scientific name in fishes

## Loading the packages

```{r message = FALSE, warning = FALSE, echo = TRUE}
# Loading packages
library(tidyverse)
```

## Loading data-set

```{r message = FALSE, warning = FALSE, echo = TRUE}
# Current standard Japanese/scientific names of all fish species recorded from Japanese waters
#https://www.museum.kagoshima-u.ac.jp/staff/motomura/jaf.html
JAFList <- read_csv("20220821_JAFList.csv")

# Species list of fisheries resources
FRA200List <- read_csv("FRA200List.csv")
```

## Linking Japanese name and scientific name
```{r message = FALSE, warning = FALSE, echo = TRUE}
no_fish <- nrow(FRA200List)

scientific_name_vec <- vector()
Family_vec <- vector()

for(i in 1:no_fish){

	target_fish <- FRA200List[i,1][[1]]
	target_fish_ID <- which(JAFList$和名==target_fish)
	scientific_name <- JAFList$学名[target_fish_ID]
	Family <-JAFList$Family[target_fish_ID]
#	gsub("\n", " ", Family)
#	if(str_extract(Family, pattern="Epinephelidae")){
#	  Family <- "Epinephelidae"
#	}

	if(!(identical(scientific_name,character(0)))){#if non-fish species
	  Family_vec[i] <- Family
	  scientific_name_vec[i] <- scientific_name
	}else{
	  Family_vec[i] <- NA
	  scientific_name_vec[i] <- NA
	}

}

FRA200List_Latin <- FRA200List %>% 
  mutate(Family = Family_vec, Scientific_name = scientific_name_vec) %>%
  arrange(Category, Family, Scientific_name)

```

## Write a list file
```{r message = FALSE, warning = FALSE, echo = TRUE}
write_csv(FRA200List_Latin, "FRA200List_Latin.csv")
```

